version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: ./sql/Dockerfile
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: geonames
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: geonames
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
